title: "Avrami Hammer, About Me"
author:
  name: "Avrami Hammer"
  summary: "I live and work in melbourne building cloud-first web solutions."
description: "A simple website showcasing who I am and what I do."
siteUrl: "https://avra.me/"
logo: "/assets/avrami-logo2.svg"
