colorWidget: &color
  widget: string
  pattern: ['#[0-9]{6}', 'Must be a Hex Colour Value']
backend:
  name: github
  repo: avra-me/avra-me.github.io
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: assets
format: yaml

collections:
  - name: config
    label: "Site Configuration"
    files:
      - label: Site Details
        name: site
        file: 'src/config/site.json'
        description: Configure your site
        fields:
          - label: "Look and Feel"
            name: theme
            widget: object
            fields:
              - {label: Site Logo, name: logo, widget: image, comment: Site title that becomes the logo}
              - label: Primary Color
                name: primary
                widget: object
                fields: [{*color, name: light, required: false},{*color, name: main},{*color, name: dark, required: false}]
              - label: Secondary Color
                name: secondary
                widget: object
                fields: [{*color, name: light, required: false},{*color, name: main},{*color, name: dark, required: false}]
#              - label: Header Gradient
#                name: gradient
#                widget: object
#                fields:
#                  - name: Gradient Points
#                    widget: list
#                    fields:
#                      - {name: position, widget: number, min: 0, max: 100, step: 1}
#                      - {name: colour, widget: string, pattern: ['#[0-9]{6}|rgba\(\d{0,3}\,\d{0,3}\,\d{0,3}\,\d{0,3}\)', 'Must be a Hex or RGBA Colour Value']}
#                  - {name: angle, widget: number, min: 0, max: 360, default: 54}
          - label: "About You and Your information"
            name: about
            widget: object
            fields:
              - {label: Prefix/Intro, name: prefix, widget: string}
              - {label: Name, name: name, widget: string}
              - {label: Caption, name: caption, widget: markdown}
              - label: Skills
                name: skills
                widget: list
                fields:
                  - {label: Headline, name: headline, widget: string}
                  - {label: Text, name: text, widget: string}
                  - {label: Icon, name: icon, widget: string}
                  - {label: Colour, name: colour, widget: string}
  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Project Link", name: "link", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}