backend:
  name: github
  repo: avra-me/avra-me.github.io
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: assets
format: yaml

collections:
  - name: config
    label: "Site Configuration"
    files:
      - label: Site Details
        name: site
        file: 'src/config/site.json'
        description: Configure how your site interacts
        fields:
          - {label: Site Logo, name: logo, widget: image, comment: Site title that becomes the logo}
          - {label: Primary Color (HEX), name: primary, widget: string, comment: "A hex colour value (the site primary colour), default #b3294e"}
          - {label: Secondary Color (HEX), name: secondary, widget: string, comment: "A hex colour value (the site secondary colour), default #4829B2"}
          - {label: Greeting, name: greeting, widget: string}
          - {label: Prefix/Intro, name: prefix, widget: string}
          - {label: Name, name: name, widget: string}
          - {label: Caption, name: caption, widget: markdown}
          - label: Skills
            name: skills
            widget: list
            fields:
              - {label: Skill Title, name: title, widget: string}
              - {label: Short Description, name: desc, widget: string}
              - {label: icon, name: icon, widget: image}
          - label: Projects
            name: projects
            widget: list
            fields:
              - {label: Project Title, name: title, widget: string}
              - {label: Short Description, name: short, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: Link, name: link, widget: string}
              - {label: Long Description, name: text, widget: markdown}

  - name: "projects"
    label: "Projects"
    folder: "src/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Project Link", name: "link", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}