colorWidget: &color
  widget: string
  pattern: ['#[0-9]{6}', 'Must be a Hex Colour Value']
backend:
  name: github
  repo: avra-me/avra-me.github.io
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/assets
public_folder: /assets
format: yaml

collections:
  - name: config
    label: "Theme"
    files:
      - label: Site Details
        name: theme
        file: 'content/config.json'
        description: Configure your site
        fields:
          - {label: Site Logo, name: logo, widget: image, comment: Site title that becomes the logo}
          - label: Primary Color
            name: primary
            widget: object
            fields: [{*color, name: light, required: false},{*color, name: main},{*color, name: dark, required: false}]
          - label: Secondary Color
            name: secondary
            widget: object
            fields: [{*color, name: light, required: false},{*color, name: main},{*color, name: dark, required: false}]
      - label: "Global Navigation"
        name: navigation
        file: 'content/common/navigation/config.json'
        fields:
          - {label: Disabled, default: false, name: disabled, widget: boolean, hint: This will enable/disable the header banner}
          - {label: Show Icon for static menus, default: false, name: staticIconEnabled, widget: boolean, hint: This effect will not be seen in preview}
      - label: "Home Page"
        name: about
        file: 'content/home/config.json'
        fields:
          - label: Header Banner
            name: header
            widget: object
            fields:
              - {label: Disabled, default: false, name: disabled, widget: boolean, hint: This will enable/disable the header banner}
              - {label: Use Gradient, name: useGradient, default: true, widget: boolean, hint: This will enable/disable the gradient background on the banner.}
              - {label: Prefix/Intro, name: prefix, widget: string, hint: "This will be placed before your name, make it welcoming"}
              - {label: Name, name: name, widget: string, hint: "What people will call you"}
              - {label: Caption, name: caption, widget: markdown, hint: "A short, snappy tag line"}
              - {label: Brand, name: brand, widget: image, hint: "A short, snappy tag line"}
      - label: "Footer Information"
        name: footer
        file: 'content/common/footer/config.json'
        fields:
          - {label: Disabled, default: false, name: disabled, widget: boolean, hint: This will enable/disable the footer}
          - {label: Site Description Header, name: header, widget: string, hint: "A short, snappy tag line"}
          - {label: Site Description, name: caption, widget: text, hint: "A short, snappy tag line"}

  - name: "experience"
    label: "Experience"
    folder: "src/pages/experience"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "type", widget: hidden, default: "experience"}
      - {label: "Start Date", name: "startDate", widget: "datetime"}
      - {label: "End Date", name: "endDate", widget: "datetime", required: false}
      - {label: "Where", name: "subTitle", widget: "string"}
      - {label: "Link", name: "link", widget: "string", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "short", widget: "text"}
      - {label: "Featured", name: "featured", widget: "boolean"}
      - {label: "Featured Image", name: "image", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "education"
    label: "Education"
    folder: "src/pages/education"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {name: "type", widget: hidden, default: "education"}
      - {label: "Sub-Title", name: "subTitle", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Start Date", name: "startDate", widget: "datetime"}
      - {label: "End Date", name: "endDate", widget: "datetime", required: false}
      - {label: "Description", name: "short", widget: "text", required: false}

  - name: "navigation"
    label: "Navigation Buttons"
    folder: content/common/navigation
    create: true
    slug: "{{title}}"
    preview_path: ""
    fields:
      - {name: "title", label: Name, widget: string, hint: "This will be the button label"}
      - {name: "icon", label: Icon, widget: string, hint: "This will be the icon displayed for mobile navigation"}
      - {name: "type", widget: hidden, default: "navigation"}
      - {name: "link", label: Link, widget: string, hint: "This will be where the button takes you"}

  - name: "tags"
    label: "Complex Tags"
    folder: content/tags
    create: true
    slug: "{{title}}"
    fields:
      - {name: "title", label: Name, widget: string, hint: "This will be the primary name for the tag"}
      - {name: "type", widget: hidden, default: "tag"}
      - {name: "alias", widget: list, label: "Other Names", hint: "This will be used to match to other records"}
      - {label: Text, name: text, widget: markdown}
      - {label: Icon, name: icon, widget: string}
      - {*color, label: Colour, name: color}
  - name: "footer"
    label: "Footer Buttons"
    folder: content/common/footer
    create: true
    slug: "{{label}}_{{type}}"
    fields:
      - {name: "label", label: Label, widget: string, hint: "This will be the primary name for the tag"}
      - {name: "type", label: Button Type, widget: select, options: [{label: "Attribution buttons", value: "attr"}, {label: "Social Media links", value: "social"}]}
      - {name: "icon", label: Icon, widget: image}
      - {name: "link", label: Link, widget: string, hint: "This will be where the button takes you"}
