colorWidget: &color
  widget: string
  pattern: ['#[0-9]{6}', 'Must be a Hex Colour Value']
backend:
  name: github
  repo: avra-me/avra-me.github.io
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/assets
public_folder: /assets
format: yaml

collections:
  - name: config
    label: "Theme"
    files:
      - label: Site Details
        name: theme
        file: 'src/config/theme.json'
        description: Configure your site
        fields:
          - {label: Site Logo, name: logo, widget: image, comment: Site title that becomes the logo}
          - label: Primary Color
            name: primary
            widget: object
            fields: [{*color, name: light, required: false},{*color, name: main},{*color, name: dark, required: false}]
          - label: Secondary Color
            name: secondary
            widget: object
            fields: [{*color, name: light, required: false},{*color, name: main},{*color, name: dark, required: false}]
      - label: "Home Page"
        name: about
        file: 'src/config/home.json'
        fields:
          - label: Header Banner
            name: header
            widget: object
            fields:
              - {label: Disabled, default: false, name: disabled, widget: boolean, hint: This will enable/disable the header banner}
              - {label: Use Gradient, name: useGradient, default: true, widget: boolean, hint: This will enable/disable the gradient background on the banner.}
              - {label: Prefix/Intro, name: prefix, widget: string, hint: "This will be placed before your name, make it welcoming"}
              - {label: Name, name: name, widget: string, hint: "What people will call you"}
              - {label: Caption, name: caption, widget: markdown, hint: "A short, snappy tag line"}
              - {label: Brand, name: brand, widget: image, hint: "A short, snappy tag line"}
          - label: Skills
            name: skills
            widget: object
            fields:
              - {label: Disabled, default: false, name: disabled, widget: boolean, hint: This will enable/disable the skills component}
              - label: Items
                name: items
                widget: list
                fields:
                  - {label: Headline, name: headline, widget: string}
                  - {label: Text, name: text, widget: string}
                  - {label: Icon, name: icon, widget: string}
                  - {*color, label: Colour, name: color}
      - label: "Footer Information"
        name: footer
        file: 'src/config/footer.json'
        fields:
          - {label: Disabled, default: false, name: disabled, widget: boolean, hint: This will enable/disable the footer}
          - {label: Site Description Header, name: header, widget: string, hint: "A short, snappy tag line"}
          - {label: Site Description, name: caption, widget: text, hint: "A short, snappy tag line"}
          - label: Social Icons
            name: icons
            widget: list
            fields:
              - {label: Icon, name: icon, widget: image, hint: "SVG files work best, see the examples."}
              - {label: Label, name: label, widget: string, "The text that will be displayed under the icon."}
              - {label: Link, name: text, widget: string, hint: "This should be the url to redirect the user to on click."}
          - label: Context Info
            name: context
            widget: list
            fields:
              - {label: Icon, name: icon, widget: image, hint: "SVG files work best, see the examples."}
              - {label: Label, name: label, widget: string, "The text that will be displayed next to the icon."}
              - {label: Link, name: link, widget: string, hint: "This should be the url to redirect the user to on click."}

  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Project Link", name: "link", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}